### ISSUE TITLE
Section 3: Movement and collisions

### ISSUE THREAD

**Issue by thompsop1sou** [RaiderSoft/semantic-godot#16]
Building off of the first part of the tutorial (showing how to make two arguing trolls), we want the next part of the tutorial to show how to set up the Level scene with the following components:
- the Map scene (can be downloaded, just need to add a background picture)
- the Gralk scene (expanded from the NPC scene already made)
- the Seraphis scene (like Gralk scene, but different picture and has a script for movement)

**Comment by defreez** [comment]
I've read through your comments. After thinking about it more, I agree that we can get away with not re-arranging the maps and collisions tutorial, and that attempting too much continuity between the sections complicates things. 

We do need to glue it together just a little bit now that section 2 is mostly finished, but we don't need to move the maps section to the top.

**Comment by thompsop1sou** [comment]
Okay, so no need to start from the NPC scene when making Gralk? Just add some comments at the beginning that explain what we're doing in light of what was completed in the previous section?

**Comment by defreez** [comment]
Yes, I think we are OK without trying to make it all flow together seamlessly. Even apart from the work to re-arrange it, there are some advantages to having distinct breaks between sections.

**Comment by thompsop1sou** [comment]
Also, I forgot to mention in the first comment that we should expand on `ChatEntity` and `ChatAI` in this section to include the `nearbyChatEntities` list and related methods, correct?

Also, should we include `StartConvo` and `EndConvo` methods in this section?
- If yes, we could start building a bit of the `ChatPlayer` script so that the player can press `Shift` to start a conversation and press `Esc` to end it. Messages from the player could be hardcoded in the `ChatPlayer` script.
- If no, we could have Gralk and Seraphis both be `ChatAI`s that are automatically connected by their parent node from the beginning.

**Comment by defreez** [comment]
> Also, I forgot to mention in the first comment that we should expand on ChatEntity and ChatAI in this section to include the nearbyChatEntities list and related methods, correct?

Yes. I started with ChatEntity.cs and ChatAI.cs from this section and removed those bits to make the Simple NPCs version. They need to come back here.

**Comment by defreez** [comment]
> Also, should we include StartConvo and EndConvo methods in this section?

If it makes sense I think we are fine to put those in here. With the Simple NPCs example out of the way there is space to put a little more here.

**Comment by thompsop1sou** [comment]
> If it makes sense I think we are fine to put those in here. With the Simple NPCs example out of the way there is space to put a little more here.

Okay, I will try adding `StartConvo` and `EndConvo` in, and perhaps the beginnings of `ChatPlayer`. If it makes this section too long, I may push them off until the next section with the UI.

**Comment by defreez** [comment]
Notes discussed earlier

- Why do we set motion mode to floating?
- Gralk is smaller now
- Put images inline. They look good and break up the text.
- Link to map.tscn
- If we tell them to put the jpg file in place before copying in map.tscn it should just work
- Mention that the placement of Gralk matters as he must block Seraphis from crossing the bridge.
- The camera limits do not need to be set (and it is better without them) because the walls are closed.
- Should we make the window bigger?
- 100x100 collision for seraphis seems to big to make it across the bridge.
