### ISSUE TITLE
Section 4: Finish ChatEntity

### ISSUE THREAD

**Issue by defreez** [RaiderSoft/semantic-godot#19]

**Comment by thompsop1sou** [comment]
For section 4, add the following:
- comments connecting to section 1 (including comment that arguing trolls scene will be broken)
- a part about adding ChatAI as a child node in the Gralk scene

**Comment by thompsop1sou** [comment]
@defreez I noticed that you have ChatEntity as section 4 and ChatPlayer as section 5. Should I merge 18-chatplayer-section into 19-section-4-finish-chatentity to reflect this change?

**Comment by defreez** [comment]
No branch 18-chatplayer-section is for issue #18 PR #25. PR #25 will merge what you do here, direction is from Section 4 to Section 5.

**Comment by defreez** [comment]
This branch should merge changes from #24 and main

**Comment by thompsop1sou** [comment]
Right, i had just realized that the files were switched around and renamed in https://github.com/RaiderSoft/semantic-godot/pull/25 but not in main or https://github.com/RaiderSoft/semantic-godot/pull/24.

Main and https://github.com/RaiderSoft/semantic-godot/pull/24 have:
- 04.a_creating_chatEntity.rst
- 04.b_using_chatEntity.rst

While https://github.com/RaiderSoft/semantic-godot/pull/25 has:
- 04.chatEntity_conversations.rst
- 05.the_player.rst

I didn't know if that was a big enough change to need to merge right away.

**Comment by thompsop1sou** [comment]
For [19-section-4-finish-chatentity](https://github.com/RaiderSoft/semantic-godot/tree/19-section-4-finish-chatentity) should I just rename "04.a_creating_chatEntity.rst" → "04.chatEntity_conversations.rst" and work on that file?

**Comment by defreez** [comment]
> For [19-section-4-finish-chatentity](https://github.com/RaiderSoft/semantic-godot/tree/19-section-4-finish-chatentity) should I just rename "04.a_creating_chatEntity.rst" → "04.chatEntity_conversations.rst" and work on that file?

Yes that works
