### ISSUE TITLE
Section 6: User Interface

### ISSUE THREAD

**Issue by defreez** [RaiderSoft/semantic-godot#20]

**Comment by thompsop1sou** [comment]
Based on the changes you made for https://github.com/RaiderSoft/semantic-godot/pull/25, I think we won't have to do much for this section, though I will probably add a few pictures.

I was thinking it would be appropriate to have a part at the end of this section that shows what's been completed up to this point. Gralk can't yet tell if the player has answered the riddle correctly (and there's no treasure chest), but everything else should be in place for the player to move around and start a conversation with Gralk. What do you think? @defreez
